# Generated by Django 3.0.6 on 2020-06-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLEEAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
