# Generated by Django 2.1.7 on 2020-06-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLEEAPP', '0003_gleedapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GLEEDAPP',
            new_name='GLEEAPP',
        ),
    ]
