# Generated by Django 2.1.7 on 2020-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLEEAPP', '0004_auto_20200618_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gleeapp',
            name='attachment',
            field=models.FileField(blank=True, upload_to='GLEEAPP/attachments/'),
        ),
    ]
