# Generated by Django 2.1.7 on 2020-06-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLEEAPP', '0005_auto_20200620_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GLEEAPP',
            new_name='IMAGES',
        ),
    ]
