# Generated by Django 2.1.7 on 2020-06-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLEEAPP', '0006_auto_20200620_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IMAGES',
            new_name='IMAGE',
        ),
    ]
