# Generated by Django 2.1.7 on 2020-06-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLEEAPP', '0007_auto_20200621_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('feature_image', models.ImageField(upload_to='GLEEAPP/images/')),
                ('attachment', models.FileField(blank=True, upload_to='GLEEAPP/attachments/')),
            ],
        ),
        migrations.DeleteModel(
            name='IMAGE',
        ),
    ]
